# Generated by Django 4.1 on 2022-11-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('intensidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('idprofesor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('idestudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('curso1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='idmateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.materia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='idprofe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.profesor'),
        ),
    ]
